name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '8,28,48 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Sync todoist
        env:
          TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}
        run: |-
          python build_readme.py
