name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Sync todos
        env:
          TODOIST_ENDPOINT: ${{ secrets.TODOIST_ENDPOINT }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |-
          npm install
          npm run sync
